### ISSUE TITLE
How to handle exceptions on server?

### ISSUE THREAD

**Issue by ady1981** [elpheria/rpc-websockets#144]
Hi,
I use wsServer like this:
```
    const wsServer = new Server({});

    wsServer.on('error', (error) => {
        logger.info(error);
    });

    // register user methods
    wsServer.register('user.createTopic', (_params) => throw Error('test-exception'));
```
So, method 'user.createTopic' throws exception.
This exception crashes the main process now.
How to proper handle exceptions on server?

**Comment by mkozjak** [comment]
Have you tried regular javascript try/catch handlers?

**Comment by ady1981** [comment]
> Have you tried regular javascript try/catch handlers?

I think that exceptions in method handler should not crash the wsServer by design. But ok, I will try the try/catch on server and decoding the errors on client.

**Comment by mkozjak** [comment]
It's not crashing wsServer in my end. It's crashing the client. The client, should, obviously be an entirely separate process.

Here's the five minute code I did to test this since you haven't provided me with a working one:
```js
var WebSocketServer = require('rpc-websockets').Server
var WebSocket = require('rpc-websockets').Client

var wsServer = new WebSocketServer({
  port: 8080,
  host: 'localhost'
})

wsServer.on('error', (error) => {
    logger.info(error);
});

// register user methods
wsServer.register('user.createTopic', (_params) => { throw Error('test-exception') });

wsServer.on('error', function(error) { console.log('error:', error) })

console.log('server configured')

setTimeout(function() {
    var ws = new WebSocket('ws://localhost:8080')

    ws.on('open', function() {
      // call an RPC method with parameters
      console.log('calling server...')

      ws.call('user.createTopic', [5, 3])
      .then(function(result) {
        console.log(result)
        ws.close()
      })
      .catch(function(error) {
          console.log('client catch:', error)
      })
    })
}, 1000)
```

Logs:
```sh
 > node a.js
server configured
calling server...
client catch: { code: -32000, message: 'Error', data: 'test-exception' }
```

So the code never threw on `wsServer.register('user.createTopic', (_params) => { throw Error('test-exception') });`

https://github.com/elpheria/rpc-websockets/blob/trunk/API.md#wscallmethod-params-timeout-ws_options---promise
https://github.com/elpheria/rpc-websockets/blob/trunk/API.md#event-error
