### ISSUE TITLE
Cannot protect event subscription

### ISSUE THREAD

**Issue by james-ct** [elpheria/rpc-websockets#78]
Hi,

I really like this library, and the auth/protected layer it puts on top, however this protection doesn't extend to the event extension, is there a reason why this is like it is? If not it would be great to see added.

**Comment by mkozjak** [comment]
Hi, @james-ct, and thanks for the kind words!

This wasn't implemented as of yet since there was no demand for it in our projects, but should be easily accomplished by checking out if the socket has its login status as authenticated. If not, it should not send an event to it. All events should be public by default.

Care to provide a PR for that? Thanks!
